// Differential test: builds each case from tests/diff/cases/*.qml with the ii-shell runtime and
// compares item geometry with what Qt produced for the same QML (tests/diff/expected/*.json,
// regenerated by tests/diff/regen.py). Builders are hand-written mirrors of the QML until
// qml2cpp exists; then they will be generated from the same files.

#include "runtime/item.h"
#include "runtime/rectangle.h"

#include "../check.h"

#include <nlohmann/json.hpp>

#include <cmath>
#include <cstdio>
#include <fstream>
#include <functional>
#include <map>
#include <memory>
#include <string>

using namespace ii;
using Json = nlohmann::json;

namespace {

  using Builder = std::function<std::unique_ptr<Item>()>;

  template <typename T> T* named(Item* parent, const char* name) {
    T* item = parent->add<T>();
    item->objectName.set(name);
    return item;
  }

  std::unique_ptr<Item> root(double w, double h) {
    auto item = std::make_unique<Item>();
    item->width.set(w);
    item->height.set(h);
    return item;
  }

  // ── Cases (mirror cases/<name>.qml) ─────────────────────────────────────────

  std::unique_ptr<Item> anchorsBasic() {
    auto r = root(400, 300);
    auto* fill = named<Rectangle>(r.get(), "fill");
    fill->anchors().fill.set(r.get());
    fill->anchors().margins.set(10);
    auto* center = named<Rectangle>(r.get(), "center");
    center->width.set(51);
    center->height.set(31);
    center->anchors().centerIn.set(r.get());
    return r;
  }

  std::unique_ptr<Item> anchorsSibling() {
    auto r = root(300, 200);
    Item* p = r.get();
    auto* a = named<Rectangle>(p, "a");
    a->x.set(20);
    a->y.set(30);
    a->width.set(50);
    a->height.set(40);

    auto* rightOfA = named<Rectangle>(p, "rightOfA");
    rightOfA->anchors().left.set(a->rightLine());
    rightOfA->anchors().leftMargin.set(5);
    rightOfA->anchors().top.set(a->topLine());
    rightOfA->width.set(30);
    rightOfA->height.set(30);

    auto* belowA = named<Rectangle>(p, "belowA");
    belowA->anchors().top.set(a->bottomLine());
    belowA->anchors().horizontalCenter.set(a->horizontalCenterLine());
    belowA->width.set(21);
    belowA->height.set(10);

    auto* stretch = named<Rectangle>(p, "stretch");
    stretch->anchors().left.set(a->rightLine());
    stretch->anchors().right.set(p->rightLine());
    stretch->anchors().rightMargin.set(7);
    stretch->y.set(100);
    stretch->height.set(5);

    auto* bottomRight = named<Rectangle>(p, "bottomRight");
    bottomRight->anchors().right.set(p->rightLine());
    bottomRight->anchors().bottom.set(p->bottomLine());
    bottomRight->anchors().margins.set(4);
    bottomRight->anchors().bottomMargin.set(9);
    bottomRight->width.set(10);
    bottomRight->height.set(10);

    auto* offsetCenter = named<Rectangle>(p, "offsetCenter");
    offsetCenter->anchors().centerIn.set(p);
    offsetCenter->anchors().horizontalCenterOffset.set(12.5);
    offsetCenter->anchors().verticalCenterOffset.set(-3);
    offsetCenter->width.set(20);
    offsetCenter->height.set(20);

    auto* vcenterOnly = named<Rectangle>(p, "vcenterOnly");
    vcenterOnly->x.set(5);
    vcenterOnly->anchors().verticalCenter.set(p->verticalCenterLine());
    vcenterOnly->width.set(8);
    vcenterOnly->height.set(13);
    return r;
  }

  std::unique_ptr<Item> anchorsFractional() {
    auto r = root(401, 301);
    auto* c1 = named<Rectangle>(r.get(), "c1");
    c1->width.set(50);
    c1->height.set(30);
    c1->anchors().centerIn.set(r.get());
    auto* c2 = named<Rectangle>(r.get(), "c2");
    c2->width.set(50.5);
    c2->height.set(30.4);
    c2->anchors().centerIn.set(r.get());

    auto* inner = named<Item>(r.get(), "inner");
    inner->x.set(10.5);
    inner->y.set(3);
    inner->width.set(99);
    inner->height.set(77);
    auto* c3 = named<Rectangle>(inner, "c3");
    c3->width.set(10);
    c3->height.set(9);
    c3->anchors().centerIn.set(inner);
    auto* c4 = named<Rectangle>(inner, "c4");
    c4->width.set(10);
    c4->height.set(9);
    c4->anchors().centerIn.set(inner);
    c4->anchors().alignWhenCentered.set(false);
    return r;
  }

  std::unique_ptr<Item> itemBasics() {
    auto r = root(200, 200);
    auto* implicitOnly = named<Item>(r.get(), "implicitOnly");
    implicitOnly->implicitWidth.set(40);
    implicitOnly->implicitHeight.set(25);
    auto* explicitWins = named<Item>(r.get(), "explicitWins");
    explicitWins->implicitWidth.set(40);
    explicitWins->implicitHeight.set(25);
    explicitWins->width.set(10);

    auto* hidden = named<Item>(r.get(), "hidden");
    hidden->visible.set(false);
    hidden->width.set(5);
    hidden->height.set(5);
    auto* hiddenChild = named<Item>(hidden, "hiddenChild");
    hiddenChild->x.set(1);
    hiddenChild->y.set(2);
    hiddenChild->width.set(3);
    hiddenChild->height.set(3);

    auto* faded = named<Item>(r.get(), "faded");
    faded->x.set(50);
    faded->y.set(60);
    faded->opacity.set(0.5);
    auto* fadedChild = named<Item>(faded, "fadedChild");
    fadedChild->x.set(7);
    fadedChild->y.set(8);
    fadedChild->width.set(1);
    fadedChild->height.set(1);
    return r;
  }

  const std::map<std::string, Builder>& cases() {
    static const std::map<std::string, Builder> all{
        {"anchors_basic", anchorsBasic},
        {"anchors_sibling", anchorsSibling},
        {"anchors_fractional", anchorsFractional},
        {"item_basics", itemBasics},
    };
    return all;
  }

  // ── Dump and compare ────────────────────────────────────────────────────────

  void collect(const Item& item, double originX, double originY, bool isRoot, Json& out) {
    const double sx = isRoot ? 0.0 : originX + item.x.peek();
    const double sy = isRoot ? 0.0 : originY + item.y.peek();
    if (!item.objectName.peek().empty()) {
      out[item.objectName.peek()] = Json{
          {"x", sx},
          {"y", sy},
          {"width", item.width.peek()},
          {"height", item.height.peek()},
          {"implicitWidth", item.implicitWidth.peek()},
          {"implicitHeight", item.implicitHeight.peek()},
          {"visible", item.effectiveVisible.peek()},
          {"opacity", item.opacity.peek()},
      };
    }
    for (const Item* child : item.childItems()) {
      collect(*child, sx, sy, false, out);
    }
  }

  bool compare(const std::string& caseName, const Json& expected, const Json& actual) {
    bool ok = true;
    for (const auto& [name, want] : expected.items()) {
      if (!actual.contains(name)) {
        std::fprintf(stderr, "  %s: missing item %s\n", caseName.c_str(), name.c_str());
        ok = false;
        continue;
      }
      const Json& got = actual[name];
      for (const auto& [key, value] : want.items()) {
        const Json& have = got[key];
        const bool same = value.is_boolean() ? value == have : std::fabs(value.get<double>() - have.get<double>()) < 1e-3;
        if (!same) {
          std::fprintf(
              stderr, "  %s: %s.%s = %s, Qt has %s\n", caseName.c_str(), name.c_str(), key.c_str(),
              have.dump().c_str(), value.dump().c_str()
          );
          ok = false;
        }
      }
    }
    return ok;
  }

  Json loadExpected(const std::string& name) {
    std::ifstream in(std::string(II_DIFF_EXPECTED_DIR) + "/" + name + ".json");
    return Json::parse(in);
  }

} // namespace

TEST("diff: every case has a builder and matches Qt") {
  for (const auto& [name, build] : cases()) {
    auto rootItem = build();
    flushPolish();
    Json actual = Json::object();
    collect(*rootItem, 0.0, 0.0, true, actual);
    const bool ok = compare(name, loadExpected(name), actual);
    CHECK(ok);
    std::fprintf(stderr, "  %s %s\n", ok ? "match" : "DIFF ", name.c_str());
  }
}

TEST_MAIN()
