"""qml2cpp: translate ii's QML into C++ for ii-shell.

  python3 -m qml2cpp deps <qml...>            dependency closure of the given files
  python3 -m qml2cpp gen  <qml...> [--deps]   generate C++ into shell/src/ii (with --deps: the closure)
  python3 -m qml2cpp todo <qml...>            JavaScript still waiting for a translation
  python3 -m qml2cpp fill <qml> <json>        store translations: {context: {"cpp": ..., "signature": ...}}
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .codegen import generate_file
from .deps import closure
from .jsexpr import Translator
from .jsstore import JsStore
from .registry import REPO, SHELL_ROOT, ComponentRef, Registry
from . import structs
from .tsys import TypeSystem
from .typemap import generated_header

OUT = REPO / "shell/src"


def _paths(args: list[str]) -> list[Path]:
    return [Path(a).resolve() if Path(a).is_absolute() or Path(a).exists() else (SHELL_ROOT / a).resolve() for a in args]


def write_component_table() -> None:
    """ii/components.{h,cpp}: every generated component that can be instantiated, by its QML path
    (for Loader.source), from what has been generated so far."""
    import re
    from .typemap import qualified_class

    entries = []
    for header in sorted((OUT / "ii").rglob("*.h")):
        text = header.read_text()
        m = re.search(r"// Generated by qml2cpp from (\S+\.qml)\.", text)
        if not m or "static " in text and "& instance();" in text:
            continue  # not a component file, or a singleton
        rel = m.group(1)
        entries.append((rel, qualified_class(ComponentRef((SHELL_ROOT / rel).resolve())), header.relative_to(OUT)))
    (OUT / "ii" / "components.h").write_text(
        "#pragma once\n// Generated by qml2cpp: the generated components by QML path.\n\n"
        '#include "runtime/component.h"\n\n#include <string_view>\n\nnamespace ii {\n\n'
        "  // The component generated from `qmlPath` (relative to the shell root), or an empty one.\n"
        "  [[nodiscard]] Component<Object> generatedComponent(std::string_view qmlPath);\n\n} // namespace ii\n")
    lines = ["// Generated by qml2cpp: the generated components by QML path.", '#include "ii/components.h"', ""]
    lines += [f'#include "{h}"' for _, _, h in entries]
    lines += ["", "#include <map>", "#include <string>", "", "namespace ii {", "",
              "  Component<Object> generatedComponent(std::string_view qmlPath) {",
              "    static const std::map<std::string, Component<Object>, std::less<>> table = {"]
    lines += [f'        {{"{rel}", Component<Object>([](Object& owner) -> Object* {{ return owner.create<::{cls}>(); }})}},'
              for rel, cls, _ in entries]
    lines += ["    };", "    const auto it = table.find(qmlPath);", "    return it == table.end() ? Component<Object>() : it->second;",
              "  }", "", "} // namespace ii", ""]
    (OUT / "ii" / "components.cpp").write_text("\n".join(lines))


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="qml2cpp")
    parser.add_argument("command", choices=["deps", "gen", "todo", "fill"])
    parser.add_argument("files", nargs="+")
    parser.add_argument("--deps", action="store_true", help="include the dependency closure")
    args = parser.parse_args(argv)

    registry = Registry()
    if args.command == "fill":
        qml, translations = _paths(args.files[:1])[0], json.loads(Path(args.files[1]).read_text())
        store = JsStore()
        unknown = store.fill(qml, translations)
        store._used[str(qml.relative_to(SHELL_ROOT))] = set(store._data(str(qml.relative_to(SHELL_ROOT))))
        store.save()
        for context in unknown:
            print(f"no recorded entry for {context}", file=sys.stderr)
        return 1 if unknown else 0
    files = _paths(args.files)
    if args.command == "deps" or args.deps:
        refs = closure(registry, files).components
        files = sorted({r.path for r in refs})
    if args.command == "deps":
        for f in files:
            print(f.relative_to(SHELL_ROOT))
        return 0

    store = JsStore()
    ts = TypeSystem(registry, store)
    tr = Translator(ts)
    totals = [0, 0]
    for path in files:
        header, source, gens = generate_file(ts, tr, store, path)
        translated, stubs = sum(g.translated for g in gens), sum(g.stubs for g in gens)
        totals[0] += translated
        totals[1] += stubs
        if args.command == "gen":
            out_h = OUT / generated_header(ComponentRef(path))
            out_h.parent.mkdir(parents=True, exist_ok=True)
            out_h.write_text(header)
            out_h.with_suffix(".cpp").write_text(source)
        print(f"{path.relative_to(SHELL_ROOT)}: {translated} translated, {stubs} to do", file=sys.stderr)
    if args.command == "gen":
        write_component_table()
        # The build's list of generated sources: everything generated so far, not just this run.
        sources = sorted(str(p.relative_to(OUT / "ii")) for p in (OUT / "ii").rglob("*.cpp"))
        (OUT / "ii" / "meson.build").write_text(
            "# Generated by qml2cpp: every generated source under shell/src/ii.\n"
            "ii_generated_sources = files(\n" + "".join(f"  '{s}',\n" for s in sources) + ")\n")
        header, unknown = structs.render(ts.var_types)
        (OUT / structs.HEADER).write_text(header)
        if unknown:
            print(f"var-types: no C++ type yet for {', '.join(unknown)}", file=sys.stderr)
    store.save()
    print(f"total: {totals[0]} translated, {totals[1]} to do", file=sys.stderr)
    if args.command == "todo":
        print(json.dumps(store.pending(), indent=1, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
